# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1422, 795)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tw_menu = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_menu.setGeometry(QtCore.QRect(-2, -3, 1431, 802))
        self.tw_menu.setStyleSheet("QTabBar::tab { \n"
"    height: 40px; \n"
"    width: 150px;  \n"
"    font: 12pt \"Ubuntu\";\n"
"}")
        self.tw_menu.setObjectName("tw_menu")
        self.tab_mainScreen = QtWidgets.QWidget()
        self.tab_mainScreen.setObjectName("tab_mainScreen")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_mainScreen)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vbl_hud = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vbl_hud.setContentsMargins(0, 0, 0, 0)
        self.vbl_hud.setObjectName("vbl_hud")
        self.gb_speedInfo = QtWidgets.QGroupBox(self.tab_mainScreen)
        self.gb_speedInfo.setGeometry(QtCore.QRect(10, 330, 300, 90))
        self.gb_speedInfo.setObjectName("gb_speedInfo")
        self.formLayoutWidget = QtWidgets.QWidget(self.gb_speedInfo)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 27, 281, 82))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.fl_speedInfo = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.fl_speedInfo.setContentsMargins(0, 0, 0, 0)
        self.fl_speedInfo.setHorizontalSpacing(42)
        self.fl_speedInfo.setObjectName("fl_speedInfo")
        self.lb_groundSpeed = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_groundSpeed.setObjectName("lb_groundSpeed")
        self.fl_speedInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_groundSpeed)
        self.le_groundSpeed = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_groundSpeed.setMinimumSize(QtCore.QSize(0, 25))
        self.le_groundSpeed.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_groundSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.le_groundSpeed.setReadOnly(True)
        self.le_groundSpeed.setObjectName("le_groundSpeed")
        self.fl_speedInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_groundSpeed)
        self.lb_airSpeed = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_airSpeed.setObjectName("lb_airSpeed")
        self.fl_speedInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_airSpeed)
        self.le_airSpeed = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_airSpeed.setMinimumSize(QtCore.QSize(0, 25))
        self.le_airSpeed.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_airSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.le_airSpeed.setReadOnly(True)
        self.le_airSpeed.setObjectName("le_airSpeed")
        self.fl_speedInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_airSpeed)
        self.gb_imuInfo = QtWidgets.QGroupBox(self.tab_mainScreen)
        self.gb_imuInfo.setGeometry(QtCore.QRect(10, 430, 300, 122))
        self.gb_imuInfo.setObjectName("gb_imuInfo")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.gb_imuInfo)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 27, 281, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.fl_imuInfo = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.fl_imuInfo.setContentsMargins(0, 0, 0, 0)
        self.fl_imuInfo.setHorizontalSpacing(67)
        self.fl_imuInfo.setObjectName("fl_imuInfo")
        self.lb_roll = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lb_roll.setObjectName("lb_roll")
        self.fl_imuInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_roll)
        self.le_roll = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_roll.setMinimumSize(QtCore.QSize(0, 25))
        self.le_roll.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.le_roll.setReadOnly(True)
        self.le_roll.setObjectName("le_roll")
        self.fl_imuInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_roll)
        self.lb_pitch = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lb_pitch.setObjectName("lb_pitch")
        self.fl_imuInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_pitch)
        self.le_pitch = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_pitch.setMinimumSize(QtCore.QSize(0, 25))
        self.le_pitch.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pitch.setReadOnly(True)
        self.le_pitch.setObjectName("le_pitch")
        self.fl_imuInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_pitch)
        self.lb_yaw = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lb_yaw.setObjectName("lb_yaw")
        self.fl_imuInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_yaw)
        self.le_yaw = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.le_yaw.setMinimumSize(QtCore.QSize(0, 25))
        self.le_yaw.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.le_yaw.setReadOnly(True)
        self.le_yaw.setObjectName("le_yaw")
        self.fl_imuInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_yaw)
        self.gb_gpsInfo = QtWidgets.QGroupBox(self.tab_mainScreen)
        self.gb_gpsInfo.setGeometry(QtCore.QRect(10, 560, 300, 154))
        self.gb_gpsInfo.setObjectName("gb_gpsInfo")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.gb_gpsInfo)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 27, 281, 192))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.fl_gpsInfo = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.fl_gpsInfo.setContentsMargins(0, 0, 0, 0)
        self.fl_gpsInfo.setHorizontalSpacing(64)
        self.fl_gpsInfo.setObjectName("fl_gpsInfo")
        self.lb_lat = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lb_lat.setObjectName("lb_lat")
        self.fl_gpsInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_lat)
        self.le_lat = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_lat.setMinimumSize(QtCore.QSize(0, 25))
        self.le_lat.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_lat.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lat.setReadOnly(True)
        self.le_lat.setObjectName("le_lat")
        self.fl_gpsInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_lat)
        self.lb_lng = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lb_lng.setObjectName("lb_lng")
        self.fl_gpsInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_lng)
        self.le_lng = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_lng.setMinimumSize(QtCore.QSize(0, 25))
        self.le_lng.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_lng.setAlignment(QtCore.Qt.AlignCenter)
        self.le_lng.setReadOnly(True)
        self.le_lng.setObjectName("le_lng")
        self.fl_gpsInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_lng)
        self.lb_alt = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lb_alt.setObjectName("lb_alt")
        self.fl_gpsInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_alt)
        self.le_alt = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_alt.setMinimumSize(QtCore.QSize(0, 25))
        self.le_alt.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_alt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_alt.setReadOnly(True)
        self.le_alt.setObjectName("le_alt")
        self.fl_gpsInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_alt)
        self.lb_sat = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lb_sat.setObjectName("lb_sat")
        self.fl_gpsInfo.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_sat)
        self.le_sat = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.le_sat.setMinimumSize(QtCore.QSize(0, 25))
        self.le_sat.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_sat.setAlignment(QtCore.Qt.AlignCenter)
        self.le_sat.setReadOnly(True)
        self.le_sat.setObjectName("le_sat")
        self.fl_gpsInfo.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_sat)
        self.bt_arm = QtWidgets.QPushButton(self.tab_mainScreen)
        self.bt_arm.setGeometry(QtCore.QRect(324, 351, 351, 32))
        self.bt_arm.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_arm.setObjectName("bt_arm")
        self.lb_miniCamera = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_miniCamera.setGeometry(QtCore.QRect(324, 10, 351, 311))
        self.lb_miniCamera.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_miniCamera.setText("")
        self.lb_miniCamera.setPixmap(QtGui.QPixmap(":/team/icons/temp_camera.png"))
        self.lb_miniCamera.setScaledContents(True)
        self.lb_miniCamera.setObjectName("lb_miniCamera")
        self.gb_flightInfo = QtWidgets.QGroupBox(self.tab_mainScreen)
        self.gb_flightInfo.setGeometry(QtCore.QRect(324, 430, 351, 90))
        self.gb_flightInfo.setObjectName("gb_flightInfo")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.gb_flightInfo)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(9, 27, 331, 61))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.fl_flightInfo = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.fl_flightInfo.setContentsMargins(0, 0, 0, 0)
        self.fl_flightInfo.setHorizontalSpacing(73)
        self.fl_flightInfo.setObjectName("fl_flightInfo")
        self.lb_flightMode = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lb_flightMode.setObjectName("lb_flightMode")
        self.fl_flightInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_flightMode)
        self.le_flightMode = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.le_flightMode.setMinimumSize(QtCore.QSize(0, 25))
        self.le_flightMode.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_flightMode.setAlignment(QtCore.Qt.AlignCenter)
        self.le_flightMode.setReadOnly(True)
        self.le_flightMode.setObjectName("le_flightMode")
        self.fl_flightInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_flightMode)
        self.lb_flightTime = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lb_flightTime.setObjectName("lb_flightTime")
        self.fl_flightInfo.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_flightTime)
        self.le_flightTime = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.le_flightTime.setMinimumSize(QtCore.QSize(0, 25))
        self.le_flightTime.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_flightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.le_flightTime.setReadOnly(True)
        self.le_flightTime.setObjectName("le_flightTime")
        self.fl_flightInfo.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_flightTime)
        self.lb_groundSpeedIndicator = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_groundSpeedIndicator.setGeometry(QtCore.QRect(325, 540, 170, 170))
        self.lb_groundSpeedIndicator.setText("")
        self.lb_groundSpeedIndicator.setPixmap(QtGui.QPixmap(":/hud/icons/speed_indicator.png"))
        self.lb_groundSpeedIndicator.setScaledContents(True)
        self.lb_groundSpeedIndicator.setObjectName("lb_groundSpeedIndicator")
        self.lb_airSpeedIndicator = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_airSpeedIndicator.setGeometry(QtCore.QRect(506, 540, 170, 170))
        self.lb_airSpeedIndicator.setText("")
        self.lb_airSpeedIndicator.setPixmap(QtGui.QPixmap(":/hud/icons/speed_indicator.png"))
        self.lb_airSpeedIndicator.setScaledContents(True)
        self.lb_airSpeedIndicator.setObjectName("lb_airSpeedIndicator")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_mainScreen)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(685, 10, 726, 701))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vbl_miniMap = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vbl_miniMap.setContentsMargins(0, 0, 0, 0)
        self.vbl_miniMap.setObjectName("vbl_miniMap")
        self.layoutWidget = QtWidgets.QWidget(self.tab_mainScreen)
        self.layoutWidget.setGeometry(QtCore.QRect(324, 387, 351, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.bl_actionButtons = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.bl_actionButtons.setContentsMargins(0, 0, 0, 0)
        self.bl_actionButtons.setObjectName("bl_actionButtons")
        self.bt_rtlMode = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_rtlMode.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_rtlMode.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_rtlMode.setObjectName("bt_rtlMode")
        self.bl_actionButtons.addWidget(self.bt_rtlMode)
        self.bt_loiterMode = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_loiterMode.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_loiterMode.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_loiterMode.setObjectName("bt_loiterMode")
        self.bl_actionButtons.addWidget(self.bt_loiterMode)
        self.bt_manualMode = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_manualMode.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_manualMode.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_manualMode.setObjectName("bt_manualMode")
        self.bl_actionButtons.addWidget(self.bt_manualMode)
        self.bt_autoMode = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_autoMode.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_autoMode.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_autoMode.setObjectName("bt_autoMode")
        self.bl_actionButtons.addWidget(self.bt_autoMode)
        self.lb_airSpeed_2 = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_airSpeed_2.setGeometry(QtCore.QRect(566, 656, 51, 31))
        self.lb_airSpeed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_airSpeed_2.setObjectName("lb_airSpeed_2")
        self.lb_groundSpeed_2 = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_groundSpeed_2.setGeometry(QtCore.QRect(385, 656, 51, 31))
        self.lb_groundSpeed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_groundSpeed_2.setObjectName("lb_groundSpeed_2")
        self.lb_airSpeedIndicatorTick = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_airSpeedIndicatorTick.setGeometry(QtCore.QRect(506, 540, 170, 170))
        self.lb_airSpeedIndicatorTick.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.lb_airSpeedIndicatorTick.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_airSpeedIndicatorTick.setText("")
        self.lb_airSpeedIndicatorTick.setPixmap(QtGui.QPixmap(":/hud/icons/speed-indicator-tick.png"))
        self.lb_airSpeedIndicatorTick.setScaledContents(True)
        self.lb_airSpeedIndicatorTick.setObjectName("lb_airSpeedIndicatorTick")
        self.cb_followUav = QtWidgets.QCheckBox(self.tab_mainScreen)
        self.cb_followUav.setGeometry(QtCore.QRect(1273, 30, 121, 23))
        self.cb_followUav.setStyleSheet("color: white;")
        self.cb_followUav.setObjectName("cb_followUav")
        self.lb_groundSpeedIndicatorTick = QtWidgets.QLabel(self.tab_mainScreen)
        self.lb_groundSpeedIndicatorTick.setGeometry(QtCore.QRect(325, 540, 170, 170))
        self.lb_groundSpeedIndicatorTick.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.lb_groundSpeedIndicatorTick.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_groundSpeedIndicatorTick.setText("")
        self.lb_groundSpeedIndicatorTick.setPixmap(QtGui.QPixmap(":/hud/icons/speed-indicator-tick.png"))
        self.lb_groundSpeedIndicatorTick.setScaledContents(True)
        self.lb_groundSpeedIndicatorTick.setObjectName("lb_groundSpeedIndicatorTick")
        self.verticalLayoutWidget.raise_()
        self.gb_speedInfo.raise_()
        self.gb_imuInfo.raise_()
        self.gb_gpsInfo.raise_()
        self.bt_arm.raise_()
        self.lb_miniCamera.raise_()
        self.gb_flightInfo.raise_()
        self.lb_groundSpeedIndicator.raise_()
        self.lb_airSpeedIndicator.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.layoutWidget.raise_()
        self.lb_airSpeedIndicatorTick.raise_()
        self.cb_followUav.raise_()
        self.lb_groundSpeedIndicatorTick.raise_()
        self.lb_airSpeed_2.raise_()
        self.lb_groundSpeed_2.raise_()
        self.tw_menu.addTab(self.tab_mainScreen, "")
        self.tab_planningMap = QtWidgets.QWidget()
        self.tab_planningMap.setObjectName("tab_planningMap")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_planningMap)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 726, 703))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vbl_planningMap = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vbl_planningMap.setContentsMargins(0, 0, 0, 0)
        self.vbl_planningMap.setObjectName("vbl_planningMap")
        self.bt_clearMap = QtWidgets.QPushButton(self.tab_planningMap)
        self.bt_clearMap.setGeometry(QtCore.QRect(21, 93, 32, 32))
        self.bt_clearMap.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/map/icons/clear_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_clearMap.setIcon(icon)
        self.bt_clearMap.setIconSize(QtCore.QSize(22, 22))
        self.bt_clearMap.setObjectName("bt_clearMap")
        self.bt_clearGeofence = QtWidgets.QPushButton(self.tab_planningMap)
        self.bt_clearGeofence.setGeometry(QtCore.QRect(21, 123, 32, 32))
        self.bt_clearGeofence.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/map/icons/clear_geofence.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_clearGeofence.setIcon(icon1)
        self.bt_clearGeofence.setIconSize(QtCore.QSize(22, 22))
        self.bt_clearGeofence.setObjectName("bt_clearGeofence")
        self.bt_clearTrack = QtWidgets.QPushButton(self.tab_planningMap)
        self.bt_clearTrack.setGeometry(QtCore.QRect(21, 153, 32, 32))
        self.bt_clearTrack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/map/icons/clear_track.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_clearTrack.setIcon(icon2)
        self.bt_clearTrack.setIconSize(QtCore.QSize(22, 22))
        self.bt_clearTrack.setObjectName("bt_clearTrack")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_planningMap)
        self.layoutWidget_2.setGeometry(QtCore.QRect(746, 176, 661, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_saveToFile = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_saveToFile.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_saveToFile.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:black;\n"
"    border-radius:6px;\n"
"    border:1px solid black;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#5a6268;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_saveToFile.setObjectName("bt_saveToFile")
        self.horizontalLayout.addWidget(self.bt_saveToFile)
        self.bt_loadFromFile = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_loadFromFile.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_loadFromFile.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:black;\n"
"    border-radius:6px;\n"
"    border:1px solid black;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#5a6268;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_loadFromFile.setObjectName("bt_loadFromFile")
        self.horizontalLayout.addWidget(self.bt_loadFromFile)
        self.bt_getFlightToUAV = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_getFlightToUAV.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_getFlightToUAV.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:black;\n"
"    border-radius:6px;\n"
"    border:1px solid black;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#5a6268;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_getFlightToUAV.setObjectName("bt_getFlightToUAV")
        self.horizontalLayout.addWidget(self.bt_getFlightToUAV)
        self.bt_loadFlightToUAV = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_loadFlightToUAV.setMinimumSize(QtCore.QSize(0, 32))
        self.bt_loadFlightToUAV.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:black;\n"
"    border-radius:6px;\n"
"    border:1px solid black;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#5a6268;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_loadFlightToUAV.setObjectName("bt_loadFlightToUAV")
        self.horizontalLayout.addWidget(self.bt_loadFlightToUAV)
        self.gb_flightInfo_2 = QtWidgets.QGroupBox(self.tab_planningMap)
        self.gb_flightInfo_2.setGeometry(QtCore.QRect(745, 13, 330, 154))
        self.gb_flightInfo_2.setObjectName("gb_flightInfo_2")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.gb_flightInfo_2)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 27, 311, 192))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.fl_flightInfo_2 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.fl_flightInfo_2.setContentsMargins(0, 0, 0, 0)
        self.fl_flightInfo_2.setHorizontalSpacing(28)
        self.fl_flightInfo_2.setObjectName("fl_flightInfo_2")
        self.lb_flightTime_2 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lb_flightTime_2.setObjectName("lb_flightTime_2")
        self.fl_flightInfo_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_flightTime_2)
        self.le_flightTime_2 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_flightTime_2.setMinimumSize(QtCore.QSize(0, 25))
        self.le_flightTime_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_flightTime_2.setAlignment(QtCore.Qt.AlignCenter)
        self.le_flightTime_2.setReadOnly(True)
        self.le_flightTime_2.setObjectName("le_flightTime_2")
        self.fl_flightInfo_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_flightTime_2)
        self.lb_flightDistance = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lb_flightDistance.setObjectName("lb_flightDistance")
        self.fl_flightInfo_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_flightDistance)
        self.le_flightDistance = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_flightDistance.setMinimumSize(QtCore.QSize(0, 25))
        self.le_flightDistance.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_flightDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.le_flightDistance.setReadOnly(True)
        self.le_flightDistance.setObjectName("le_flightDistance")
        self.fl_flightInfo_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_flightDistance)
        self.lb_totalFlightTime = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lb_totalFlightTime.setObjectName("lb_totalFlightTime")
        self.fl_flightInfo_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_totalFlightTime)
        self.le_totalFlightTime = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_totalFlightTime.setMinimumSize(QtCore.QSize(0, 25))
        self.le_totalFlightTime.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_totalFlightTime.setAlignment(QtCore.Qt.AlignCenter)
        self.le_totalFlightTime.setReadOnly(True)
        self.le_totalFlightTime.setObjectName("le_totalFlightTime")
        self.fl_flightInfo_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_totalFlightTime)
        self.lb_totalFlightDistance = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lb_totalFlightDistance.setObjectName("lb_totalFlightDistance")
        self.fl_flightInfo_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_totalFlightDistance)
        self.le_totalFlightDistance = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.le_totalFlightDistance.setMinimumSize(QtCore.QSize(0, 25))
        self.le_totalFlightDistance.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_totalFlightDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.le_totalFlightDistance.setReadOnly(True)
        self.le_totalFlightDistance.setObjectName("le_totalFlightDistance")
        self.fl_flightInfo_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_totalFlightDistance)
        self.gb_geofence = QtWidgets.QGroupBox(self.tab_planningMap)
        self.gb_geofence.setGeometry(QtCore.QRect(1085, 13, 321, 122))
        self.gb_geofence.setObjectName("gb_geofence")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.gb_geofence)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 27, 301, 98))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.fl_geofence = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.fl_geofence.setContentsMargins(0, 0, 0, 0)
        self.fl_geofence.setHorizontalSpacing(2)
        self.fl_geofence.setObjectName("fl_geofence")
        self.lb_minAlt = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.lb_minAlt.setObjectName("lb_minAlt")
        self.fl_geofence.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_minAlt)
        self.le_minAlt = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.le_minAlt.setMinimumSize(QtCore.QSize(0, 25))
        self.le_minAlt.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_minAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_minAlt.setObjectName("le_minAlt")
        self.fl_geofence.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_minAlt)
        self.lb_maxAlt = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.lb_maxAlt.setObjectName("lb_maxAlt")
        self.fl_geofence.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_maxAlt)
        self.le_maxAlt = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.le_maxAlt.setMinimumSize(QtCore.QSize(0, 25))
        self.le_maxAlt.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_maxAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_maxAlt.setObjectName("le_maxAlt")
        self.fl_geofence.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_maxAlt)
        self.cb_geofenceOnOff = QtWidgets.QCheckBox(self.formLayoutWidget_6)
        self.cb_geofenceOnOff.setStyleSheet("")
        self.cb_geofenceOnOff.setObjectName("cb_geofenceOnOff")
        self.fl_geofence.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cb_geofenceOnOff)
        self.bt_completeGeofence = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.bt_completeGeofence.setMinimumSize(QtCore.QSize(0, 20))
        self.bt_completeGeofence.setObjectName("bt_completeGeofence")
        self.fl_geofence.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bt_completeGeofence)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_planningMap)
        self.layoutWidget1.setGeometry(QtCore.QRect(1095, 143, 317, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_wpRadius = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_wpRadius.setObjectName("lb_wpRadius")
        self.horizontalLayout_3.addWidget(self.lb_wpRadius)
        self.le_wpRadius = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_wpRadius.setMinimumSize(QtCore.QSize(0, 25))
        self.le_wpRadius.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_wpRadius.setAlignment(QtCore.Qt.AlignCenter)
        self.le_wpRadius.setObjectName("le_wpRadius")
        self.horizontalLayout_3.addWidget(self.le_wpRadius)
        self.lb_defaultAlt = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_defaultAlt.setObjectName("lb_defaultAlt")
        self.horizontalLayout_3.addWidget(self.lb_defaultAlt)
        self.le_defaultAlt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_defaultAlt.setMinimumSize(QtCore.QSize(0, 25))
        self.le_defaultAlt.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_defaultAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_defaultAlt.setObjectName("le_defaultAlt")
        self.horizontalLayout_3.addWidget(self.le_defaultAlt)
        self.tw_waypoints = QtWidgets.QTableWidget(self.tab_planningMap)
        self.tw_waypoints.setGeometry(QtCore.QRect(745, 220, 661, 491))
        self.tw_waypoints.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tw_waypoints.setStyleSheet("QTableWidget{\n"
"    border-top: 1px solid lightgray;\n"
"    outline: 0;\n"
"    selection-background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    border-left: 1px solid lightgray;\n"
"    border-bottom: 1px solid lightgray;\n"
"    color: black;\n"
"}\n"
"\n"
"QTableWidget::last-child{\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QTableWidget::item:focus{\n"
"    background-color:transparent;\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(238, 238, 236);\n"
"    padding: 4px;\n"
"    font-size: 9pt;\n"
"    height: 18px;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-left: 1px solid lightgray;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #fffff8;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background:white;\n"
"    border-radius: 12px;\n"
"    width:6px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"   background: gray;\n"
"    min-height: 0px;\n"
"    border-radius: 12px;\n"
"}")
        self.tw_waypoints.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tw_waypoints.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tw_waypoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tw_waypoints.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tw_waypoints.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_waypoints.setShowGrid(False)
        self.tw_waypoints.setRowCount(0)
        self.tw_waypoints.setObjectName("tw_waypoints")
        self.tw_waypoints.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_waypoints.setHorizontalHeaderItem(9, item)
        self.tw_waypoints.horizontalHeader().setHighlightSections(True)
        self.tw_waypoints.horizontalHeader().setSortIndicatorShown(False)
        self.tw_waypoints.horizontalHeader().setStretchLastSection(False)
        self.tw_waypoints.verticalHeader().setHighlightSections(True)
        self.tw_waypoints.verticalHeader().setStretchLastSection(False)
        self.line = QtWidgets.QFrame(self.tab_planningMap)
        self.line.setGeometry(QtCore.QRect(736, 220, 20, 491))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_planningMap)
        self.line_2.setGeometry(QtCore.QRect(1397, 220, 20, 491))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab_planningMap)
        self.line_3.setGeometry(QtCore.QRect(745, 710, 661, 3))
        self.line_3.setStyleSheet("border-left: 1px solid lightgray;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab_planningMap)
        self.line_4.setGeometry(QtCore.QRect(746, 220, 661, 3))
        self.line_4.setStyleSheet("border-left: 1px solid lightgray;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tw_menu.addTab(self.tab_planningMap, "")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_parameters)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, -1, 1423, 724))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vl_parameters = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vl_parameters.setContentsMargins(0, 0, 0, 0)
        self.vl_parameters.setObjectName("vl_parameters")
        self.tw_menu.addTab(self.tab_parameters, "")
        self.tab_camera = QtWidgets.QWidget()
        self.tab_camera.setObjectName("tab_camera")
        self.lb_camera = QtWidgets.QLabel(self.tab_camera)
        self.lb_camera.setGeometry(QtCore.QRect(10, 10, 1246, 701))
        self.lb_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_camera.setText("")
        self.lb_camera.setObjectName("lb_camera")
        self.cb_resolution = QtWidgets.QComboBox(self.tab_camera)
        self.cb_resolution.setEnabled(True)
        self.cb_resolution.setGeometry(QtCore.QRect(1270, 270, 139, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_resolution.sizePolicy().hasHeightForWidth())
        self.cb_resolution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_resolution.setFont(font)
        self.cb_resolution.setToolTip("")
        self.cb_resolution.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_resolution.setObjectName("cb_resolution")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.bt_cameraStart = QtWidgets.QPushButton(self.tab_camera)
        self.bt_cameraStart.setGeometry(QtCore.QRect(1269, 310, 141, 51))
        self.bt_cameraStart.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_cameraStart.setFont(font)
        self.bt_cameraStart.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color:black;\n"
"    border-radius:6px;\n"
"    border:1px solid black;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:#5a6268;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_cameraStart.setObjectName("bt_cameraStart")
        self.tw_menu.addTab(self.tab_camera, "")
        self.bt_connect = QtWidgets.QPushButton(self.centralwidget)
        self.bt_connect.setGeometry(QtCore.QRect(1120, 5, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_connect.sizePolicy().hasHeightForWidth())
        self.bt_connect.setSizePolicy(sizePolicy)
        self.bt_connect.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(54, 161, 30);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(54, 161, 30);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color: rgb(54, 141, 30);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_connect.setFlat(False)
        self.bt_connect.setObjectName("bt_connect")
        self.sw_connectionCB = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_connectionCB.setGeometry(QtCore.QRect(840, 5, 271, 29))
        self.sw_connectionCB.setObjectName("sw_connectionCB")
        self.wid_simConnect = QtWidgets.QWidget()
        self.wid_simConnect.setObjectName("wid_simConnect")
        self.cb_connectionAdress = QtWidgets.QComboBox(self.wid_simConnect)
        self.cb_connectionAdress.setEnabled(True)
        self.cb_connectionAdress.setGeometry(QtCore.QRect(0, 0, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_connectionAdress.sizePolicy().hasHeightForWidth())
        self.cb_connectionAdress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_connectionAdress.setFont(font)
        self.cb_connectionAdress.setToolTip("")
        self.cb_connectionAdress.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_connectionAdress.setObjectName("cb_connectionAdress")
        self.cb_connectionAdress.addItem("")
        self.cb_connectionAdress.addItem("")
        self.cb_port = QtWidgets.QComboBox(self.wid_simConnect)
        self.cb_port.setEnabled(True)
        self.cb_port.setGeometry(QtCore.QRect(138, 0, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_port.sizePolicy().hasHeightForWidth())
        self.cb_port.setSizePolicy(sizePolicy)
        self.cb_port.setToolTip("")
        self.cb_port.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_port.setObjectName("cb_port")
        self.cb_port.addItem("")
        self.cb_port.addItem("")
        self.cb_port.addItem("")
        self.sw_connectionCB.addWidget(self.wid_simConnect)
        self.wid_normalConnect = QtWidgets.QWidget()
        self.wid_normalConnect.setObjectName("wid_normalConnect")
        self.cb_connectionType = QtWidgets.QComboBox(self.wid_normalConnect)
        self.cb_connectionType.setEnabled(True)
        self.cb_connectionType.setGeometry(QtCore.QRect(0, 0, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_connectionType.sizePolicy().hasHeightForWidth())
        self.cb_connectionType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cb_connectionType.setFont(font)
        self.cb_connectionType.setToolTip("")
        self.cb_connectionType.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_connectionType.setObjectName("cb_connectionType")
        self.cb_connectionType.addItem("")
        self.cb_connectionType.addItem("")
        self.cb_connectionType.addItem("")
        self.cb_baudRate = QtWidgets.QComboBox(self.wid_normalConnect)
        self.cb_baudRate.setEnabled(True)
        self.cb_baudRate.setGeometry(QtCore.QRect(138, 0, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_baudRate.sizePolicy().hasHeightForWidth())
        self.cb_baudRate.setSizePolicy(sizePolicy)
        self.cb_baudRate.setToolTip("")
        self.cb_baudRate.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_baudRate.setObjectName("cb_baudRate")
        self.cb_baudRate.addItem("")
        self.cb_baudRate.addItem("")
        self.cb_baudRate.addItem("")
        self.sw_connectionCB.addWidget(self.wid_normalConnect)
        self.bt_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.bt_minimize.setGeometry(QtCore.QRect(1296, -1, 42, 37))
        self.bt_minimize.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: none;\n"
"    border-left: 1px solid #ababab;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color : rgb(239, 41, 41);\n"
"}")
        self.bt_minimize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/window/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimize.setIcon(icon3)
        self.bt_minimize.setIconSize(QtCore.QSize(20, 20))
        self.bt_minimize.setObjectName("bt_minimize")
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(1380, -1, 42, 37))
        self.bt_close.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color : rgb(239, 41, 41);\n"
"}")
        self.bt_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/window/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon4)
        self.bt_close.setIconSize(QtCore.QSize(20, 20))
        self.bt_close.setObjectName("bt_close")
        self.bt_maximize = QtWidgets.QPushButton(self.centralwidget)
        self.bt_maximize.setGeometry(QtCore.QRect(1338, -1, 42, 37))
        self.bt_maximize.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color : rgb(239, 41, 41);\n"
"}")
        self.bt_maximize.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/window/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximize.setIcon(icon5)
        self.bt_maximize.setIconSize(QtCore.QSize(20, 20))
        self.bt_maximize.setObjectName("bt_maximize")
        self.cb_simulation = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_simulation.setGeometry(QtCore.QRect(744, 5, 91, 25))
        self.cb_simulation.setStyleSheet("")
        self.cb_simulation.setObjectName("cb_simulation")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 760, 1421, 35))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.bl_statusBar = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.bl_statusBar.setContentsMargins(0, 0, 0, 0)
        self.bl_statusBar.setSpacing(0)
        self.bl_statusBar.setObjectName("bl_statusBar")
        self.lb_teamName = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_teamName.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_teamName.setFont(font)
        self.lb_teamName.setStyleSheet("QLabel {\n"
"    font: 11pt \"Ubuntu\";\n"
"    background-color: #ECECEC;\n"
"    border-right: 1px solid #ababab;\n"
"    border-top: 1px solid #ababab;\n"
"}")
        self.lb_teamName.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_teamName.setObjectName("lb_teamName")
        self.bl_statusBar.addWidget(self.lb_teamName)
        self.lb_status = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_status.setFont(font)
        self.lb_status.setStyleSheet("QLabel {\n"
"    font: 9pt \"Ubuntu\";\n"
"    color: red;\n"
"    background-color: #ECECEC;\n"
"    border-right: 1px solid #ababab;\n"
"    border-top: 1px solid #ababab;\n"
"}")
        self.lb_status.setText("")
        self.lb_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_status.setObjectName("lb_status")
        self.bl_statusBar.addWidget(self.lb_status)
        self.lb_date = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_date.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_date.setFont(font)
        self.lb_date.setStyleSheet("QLabel {\n"
"    font: 11pt \"Ubuntu\";\n"
"    background-color: #ECECEC;\n"
"    border-top: 1px solid #ababab;\n"
"}")
        self.lb_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_date.setObjectName("lb_date")
        self.bl_statusBar.addWidget(self.lb_date)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tw_menu.setCurrentIndex(1)
        self.sw_connectionCB.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_speedInfo.setTitle(_translate("MainWindow", "Hız Bilgileri"))
        self.lb_groundSpeed.setText(_translate("MainWindow", "Yer Hızı (m/s)"))
        self.lb_airSpeed.setText(_translate("MainWindow", "Hava Hızı (m/s)"))
        self.gb_imuInfo.setTitle(_translate("MainWindow", "IMU Verileri"))
        self.lb_roll.setText(_translate("MainWindow", "Roll (deg)"))
        self.lb_pitch.setText(_translate("MainWindow", "Pitch (deg)"))
        self.lb_yaw.setText(_translate("MainWindow", "Yaw (deg)"))
        self.gb_gpsInfo.setTitle(_translate("MainWindow", "GPS Verileri"))
        self.lb_lat.setText(_translate("MainWindow", "Enlem"))
        self.lb_lng.setText(_translate("MainWindow", "Boylam"))
        self.lb_alt.setText(_translate("MainWindow", "İrtifa (m)"))
        self.lb_sat.setText(_translate("MainWindow", "Uydu Sayısı"))
        self.bt_arm.setText(_translate("MainWindow", "ARM"))
        self.gb_flightInfo.setTitle(_translate("MainWindow", "Uçuş Bilgileri"))
        self.lb_flightMode.setText(_translate("MainWindow", "Uçuş Modu:"))
        self.lb_flightTime.setText(_translate("MainWindow", "Uçuş Süresi:      "))
        self.bt_rtlMode.setText(_translate("MainWindow", "RTL"))
        self.bt_loiterMode.setText(_translate("MainWindow", "LOITER"))
        self.bt_manualMode.setText(_translate("MainWindow", "MANUAL"))
        self.bt_autoMode.setText(_translate("MainWindow", "AUTO"))
        self.lb_airSpeed_2.setText(_translate("MainWindow", "Hava Hızı\n"
"(m/s)"))
        self.lb_groundSpeed_2.setText(_translate("MainWindow", "Yer Hızı\n"
"(m/s)"))
        self.cb_followUav.setText(_translate("MainWindow", "Uçağı Takip Et"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_mainScreen), _translate("MainWindow", "Ana Ekran"))
        self.bt_saveToFile.setText(_translate("MainWindow", "Görevi Dosyaya Kaydet"))
        self.bt_loadFromFile.setText(_translate("MainWindow", "Dosyadan Görev Yükle"))
        self.bt_getFlightToUAV.setText(_translate("MainWindow", "Uçaktan Görev Çek"))
        self.bt_loadFlightToUAV.setText(_translate("MainWindow", "Uçağa Görev Yükle"))
        self.gb_flightInfo_2.setTitle(_translate("MainWindow", "Uçuş Bilgileri"))
        self.lb_flightTime_2.setText(_translate("MainWindow", "Uçuş Süresi:"))
        self.lb_flightDistance.setText(_translate("MainWindow", "Uçuşta Alınan Mesafe:"))
        self.le_flightDistance.setText(_translate("MainWindow", "-"))
        self.lb_totalFlightTime.setText(_translate("MainWindow", "Toplam Uçuş Süresi:"))
        self.lb_totalFlightDistance.setText(_translate("MainWindow", "Toplam Alınan Mesafe:"))
        self.le_totalFlightDistance.setText(_translate("MainWindow", "-"))
        self.gb_geofence.setTitle(_translate("MainWindow", "Geofence"))
        self.lb_minAlt.setText(_translate("MainWindow", "Minimum İrtifa"))
        self.lb_maxAlt.setText(_translate("MainWindow", "Maksimum İrtifa"))
        self.cb_geofenceOnOff.setText(_translate("MainWindow", "Geofence Açık/Kapalı"))
        self.bt_completeGeofence.setText(_translate("MainWindow", "Tamamlandı"))
        self.lb_wpRadius.setText(_translate("MainWindow", "WP Yarıçapı:"))
        self.le_wpRadius.setText(_translate("MainWindow", "30"))
        self.lb_defaultAlt.setText(_translate("MainWindow", "Varsayılan İrtifa:"))
        self.le_defaultAlt.setText(_translate("MainWindow", "30"))
        item = self.tw_waypoints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tw_waypoints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Komut"))
        item = self.tw_waypoints.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Param1"))
        item = self.tw_waypoints.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Param2"))
        item = self.tw_waypoints.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Param3"))
        item = self.tw_waypoints.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Param4"))
        item = self.tw_waypoints.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Enlem"))
        item = self.tw_waypoints.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Boylam"))
        item = self.tw_waypoints.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "İrtifa"))
        item = self.tw_waypoints.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Sil?"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_planningMap), _translate("MainWindow", "Uçuş Planı"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_parameters), _translate("MainWindow", "Parametre"))
        self.cb_resolution.setCurrentText(_translate("MainWindow", "        Çözünürlük", "asdsad"))
        self.cb_resolution.setItemText(0, _translate("MainWindow", "        Çözünürlük"))
        self.cb_resolution.setItemText(1, _translate("MainWindow", "1080p"))
        self.cb_resolution.setItemText(2, _translate("MainWindow", "720p"))
        self.cb_resolution.setItemText(3, _translate("MainWindow", "480p"))
        self.cb_resolution.setItemText(4, _translate("MainWindow", "360p"))
        self.cb_resolution.setItemText(5, _translate("MainWindow", "240p"))
        self.cb_resolution.setItemText(6, _translate("MainWindow", "144p"))
        self.bt_cameraStart.setText(_translate("MainWindow", "Görüntü İletimini\n"
"Başlat"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_camera), _translate("MainWindow", "Kamera"))
        self.bt_connect.setText(_translate("MainWindow", "Bağlan"))
        self.cb_connectionAdress.setCurrentText(_translate("MainWindow", "Bağlantı Adresi", "asdsad"))
        self.cb_connectionAdress.setItemText(0, _translate("MainWindow", "Bağlantı Adresi"))
        self.cb_connectionAdress.setItemText(1, _translate("MainWindow", "127.0.0.1"))
        self.cb_port.setCurrentText(_translate("MainWindow", "Port", "asdsad"))
        self.cb_port.setItemText(0, _translate("MainWindow", "Port"))
        self.cb_port.setItemText(1, _translate("MainWindow", "14550"))
        self.cb_port.setItemText(2, _translate("MainWindow", "14551"))
        self.cb_connectionType.setCurrentText(_translate("MainWindow", "Bağlantı Türü", "asdsad"))
        self.cb_connectionType.setItemText(0, _translate("MainWindow", "Bağlantı Türü"))
        self.cb_connectionType.setItemText(1, _translate("MainWindow", "TCP"))
        self.cb_connectionType.setItemText(2, _translate("MainWindow", "UDP"))
        self.cb_baudRate.setCurrentText(_translate("MainWindow", "Bant Genişliği", "asdsad"))
        self.cb_baudRate.setItemText(0, _translate("MainWindow", "Bant Genişliği"))
        self.cb_baudRate.setItemText(1, _translate("MainWindow", "57600"))
        self.cb_baudRate.setItemText(2, _translate("MainWindow", "115200"))
        self.cb_simulation.setText(_translate("MainWindow", "Simülasyon"))
        self.lb_teamName.setText(_translate("MainWindow", "Hürtürk İHA Takımı"))
        self.lb_date.setText(_translate("MainWindow", "31 Ocak 2021 - 12:12:12"))
import icon_rc
