# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indicator_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 310)
        self.lb_background = QtWidgets.QLabel(Form)
        self.lb_background.setEnabled(True)
        self.lb_background.setGeometry(QtCore.QRect(0, 0, 300, 310))
        self.lb_background.setText("")
        self.lb_background.setObjectName("lb_background")
        self.lb_centerLine = QtWidgets.QLabel(Form)
        self.lb_centerLine.setGeometry(QtCore.QRect(50, 153, 200, 4))
        self.lb_centerLine.setStyleSheet("background-color: rgb(0, 0, 0, 0);")
        self.lb_centerLine.setText("")
        self.lb_centerLine.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_centerLine.setObjectName("lb_centerLine")
        self.lb_gpsStatus = QtWidgets.QLabel(Form)
        self.lb_gpsStatus.setGeometry(QtCore.QRect(295, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lb_gpsStatus.setFont(font)
        self.lb_gpsStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 17px;")
        self.lb_gpsStatus.setObjectName("lb_gpsStatus")
        self.lb_connectionBar = QtWidgets.QLabel(Form)
        self.lb_connectionBar.setGeometry(QtCore.QRect(229, 282, 15, 15))
        self.lb_connectionBar.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.lb_connectionBar.setText("")
        self.lb_connectionBar.setPixmap(QtGui.QPixmap(":/hud/icons/high_connection.png"))
        self.lb_connectionBar.setScaledContents(True)
        self.lb_connectionBar.setObjectName("lb_connectionBar")
        self.lb_connectionText = QtWidgets.QLabel(Form)
        self.lb_connectionText.setGeometry(QtCore.QRect(249, 281, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lb_connectionText.setFont(font)
        self.lb_connectionText.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lb_connectionText.setObjectName("lb_connectionText")
        self.lb_indicatorRoll = QtWidgets.QLabel(Form)
        self.lb_indicatorRoll.setGeometry(QtCore.QRect(10, 9, 280, 291))
        self.lb_indicatorRoll.setStyleSheet("background-color: rgb(0, 0, 0, 0);")
        self.lb_indicatorRoll.setText("")
        self.lb_indicatorRoll.setPixmap(QtGui.QPixmap(":/hud/icons/roll_bar.png"))
        self.lb_indicatorRoll.setScaledContents(True)
        self.lb_indicatorRoll.setObjectName("lb_indicatorRoll")
        self.lb_rollPointer = QtWidgets.QLabel(Form)
        self.lb_rollPointer.setGeometry(QtCore.QRect(140, 34, 20, 20))
        self.lb_rollPointer.setStyleSheet("background-color: rgb(0, 0, 0, 0);")
        self.lb_rollPointer.setText("")
        self.lb_rollPointer.setPixmap(QtGui.QPixmap(":/hud/icons/yaw_tick.png"))
        self.lb_rollPointer.setScaledContents(True)
        self.lb_rollPointer.setObjectName("lb_rollPointer")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(105, 65, 90, 221))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lb_pitch = QtWidgets.QLabel(self.frame)
        self.lb_pitch.setGeometry(QtCore.QRect(-1, -295, 91, 771))
        self.lb_pitch.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.lb_pitch.setText("")
        self.lb_pitch.setPixmap(QtGui.QPixmap(":/hud/icons/pitch_bar.png"))
        self.lb_pitch.setScaledContents(True)
        self.lb_pitch.setObjectName("lb_pitch")
        self.lb_armStatus = QtWidgets.QLabel(Form)
        self.lb_armStatus.setGeometry(QtCore.QRect(10, 281, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lb_armStatus.setFont(font)
        self.lb_armStatus.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lb_armStatus.setObjectName("lb_armStatus")
        self.lb_background.raise_()
        self.lb_gpsStatus.raise_()
        self.lb_indicatorRoll.raise_()
        self.lb_rollPointer.raise_()
        self.frame.raise_()
        self.lb_centerLine.raise_()
        self.lb_connectionText.raise_()
        self.lb_connectionBar.raise_()
        self.lb_armStatus.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_gpsStatus.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">3D FİX</span></p></body></html>"))
        self.lb_connectionText.setText(_translate("Form", "98%"))
        self.lb_armStatus.setText(_translate("Form", "DISARMED"))
import icon_rc
