# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1419, 731)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        Form.setPalette(palette)
        self.lb_search = QtWidgets.QLabel(Form)
        self.lb_search.setGeometry(QtCore.QRect(12, 20, 71, 29))
        self.lb_search.setObjectName("lb_search")
        self.le_search = QtWidgets.QLineEdit(Form)
        self.le_search.setGeometry(QtCore.QRect(65, 20, 221, 29))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.le_search.setPalette(palette)
        self.le_search.setObjectName("le_search")
        self.lw_parameterFamily = QtWidgets.QListWidget(Form)
        self.lw_parameterFamily.setGeometry(QtCore.QRect(8, 60, 278, 656))
        self.lw_parameterFamily.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lw_parameterFamily.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lw_parameterFamily.setObjectName("lw_parameterFamily")
        self.tw_parameters = QtWidgets.QTableWidget(Form)
        self.tw_parameters.setGeometry(QtCore.QRect(295, 60, 1114, 656))
        self.tw_parameters.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tw_parameters.setStyleSheet("QTableWidget{\n"
"    border-top: 1px solid lightgray;\n"
"    border-right: 1px solid lightgray;\n"
"    outline: 0;\n"
"}\n"
"QTableCornerButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QTableWidget::item{\n"
"    border-left: 1px solid lightgray;\n"
"    border-bottom: 1px solid lightgray;\n"
"}\n"
"\n"
"QTableWidget::item:focus{\n"
"    background-color: rgba(255, 0, 0, 0.1);\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(238, 238, 236);\n"
"    padding: 4px;\n"
"    font-size: 9pt;\n"
"    height: 18px;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-left: 1px solid lightgray;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #fffff8;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background:white;\n"
"    border-radius: 12px;\n"
"    width:6px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"   background: gray;\n"
"    min-height: 0px;\n"
"    border-radius: 12px;\n"
"}")
        self.tw_parameters.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tw_parameters.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tw_parameters.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tw_parameters.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_parameters.setShowGrid(False)
        self.tw_parameters.setRowCount(6)
        self.tw_parameters.setObjectName("tw_parameters")
        self.tw_parameters.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_parameters.setHorizontalHeaderItem(2, item)
        self.tw_parameters.horizontalHeader().setHighlightSections(True)
        self.tw_parameters.horizontalHeader().setSortIndicatorShown(False)
        self.tw_parameters.verticalHeader().setHighlightSections(True)
        self.tw_parameters.verticalHeader().setStretchLastSection(False)
        self.bt_resetParameters = QtWidgets.QPushButton(Form)
        self.bt_resetParameters.setGeometry(QtCore.QRect(296, 20, 171, 29))
        self.bt_resetParameters.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_resetParameters.setObjectName("bt_resetParameters")
        self.bt_saveParameters = QtWidgets.QPushButton(Form)
        self.bt_saveParameters.setGeometry(QtCore.QRect(479, 20, 171, 29))
        self.bt_saveParameters.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_saveParameters.setObjectName("bt_saveParameters")
        self.bt_loadParameters = QtWidgets.QPushButton(Form)
        self.bt_loadParameters.setGeometry(QtCore.QRect(659, 20, 231, 29))
        self.bt_loadParameters.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color:  rgb(50,50,50);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_loadParameters.setObjectName("bt_loadParameters")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_search.setText(_translate("Form", "Arama:"))
        item = self.tw_parameters.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.verticalHeaderItem(5)
        item.setText(_translate("Form", "New Row"))
        item = self.tw_parameters.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Parametre"))
        item = self.tw_parameters.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Değer"))
        item = self.tw_parameters.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Açıklama"))
        self.bt_resetParameters.setText(_translate("Form", "Parametreleri Sıfırla"))
        self.bt_saveParameters.setText(_translate("Form", "Parametreleri Kaydet"))
        self.bt_loadParameters.setText(_translate("Form", "Parametreleri Dosyadan Yükle"))
